# Generated by Django 4.1.2 on 2023-10-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='description',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
