# Generated by Django 4.1.2 on 2023-10-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindr', '0002_videomodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
