# Generated by Django 4.1.2 on 2023-11-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindr', '0004_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchesmodel',
            name='ephemeral',
            field=models.BooleanField(default=False),
        ),
    ]
